### ISSUE TITLE
AnyOf support

### ISSUE THREAD

**Issue by riccardo1991** [alecthomas/jsonschema#18]
Hello, it seems this package is not supporting yet the AnyOf, is it right?

**Comment by alecthomas** [comment]
How would that work exactly, on the Go side?

**Comment by bunyk** [comment]
@alecthomas  We are working on something like this:

```go
type Professional struct {
	developer *Developer
	qa        *QA
}

func (p Professional) AnyOf() []reflect.StructField {
	return AnyOfFieldsIn(p, "developer", "qa")
}

type Developer struct {
	Profession string `jsonschema:"pattern:^software developer$"`
	Languages  []string
}

type QA struct {
	Profession string `jsonschema:"pattern:^QA$"`
	Automation bool
}

func AnyOfFieldsIn(p interface{}, names ...string) []reflect.StructField {
	t := reflect.TypeOf(p)
	res := make([]reflect.StructField, 0)
	for _, name := range names {
		field, ok := t.FieldByName(name)
		if !ok {
			panic(fmt.Sprintf("No field named %s in struct %v", name, p))
		}
		res = append(res, field)
	}
	return res
}
```
Of course we probably would also need to define (un)?marshall methods for json to not have one additional nesting level. (Too bad  that Go don't have some kind of union types)

**Comment by alecthomas** [comment]
I think AnyOf support would be interesting, but I don't like exposing reflect as part of the API. Users should not have to interact with reflect at all.
