### ISSUE TITLE
Support for multiple types

### ISSUE THREAD

**Issue by williammartin** [alecthomas/jsonschema#30]
The jsonschema spec states for the `type` keyword that:

```
The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

String values MUST be one of the six primitive types ("null", "boolean", "object", "array", "number", or "string"), or "integer" which matches any number with a zero fractional part.

An instance validates if and only if the instance is in any of the sets listed for this keyword.
```

https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1

Unfortunately, it seems like `jsonschema` only supports the string type? https://github.com/alecthomas/jsonschema/blob/master/reflect.go#L58

Any thoughts on how we might fix this?

**Comment by alecthomas** [comment]
No, the library supports different types, inferred from the Go type. What’s the use case you’re trying to solve?

**Comment by williammartin** [comment]
Yeh so I'm trying to capture a `command` (in the linux sense), which can either be represented as a string or array of strings. If I were to write the jsonschema by hand I would probably take advantage of `type` being an array and write something like:

```
"type": [
  "string",
  "array"
]
```

**Comment by alecthomas** [comment]
Mmm. While I can see what you're saying, that really defeats the purpose of using this library. As a hypothetical example, if you had the following, how would you specify the types of the array elements?

```go
Field interface{} `jsonschema:",array"`
```

**Comment by alecthomas** [comment]
No response.
