### ISSUE TITLE
Allow configurable schema defaults for struct types

### ISSUE THREAD

**Issue by ekinanp** [alecthomas/jsonschema#41]
The existing code has defaults for https://github.com/alecthomas/jsonschema/blob/master/reflect.go#L148-L150. It would be nice if I could pass my own defaults to the Reflector on top of the existing defaults. That lets me generate suitable JSON schemas for something like

```
type Time time.Time
type A struct {
  T Time
}
```

where I have no control over `A` or `Time` because they are included in a dependency. Note that `jsonschema` treats `A#T` as a struct instead of a `time.Time` object, which is the correct behavior since `jsonschema`'s only aware of `time.Time`.

Don't know what the API would look like. Maybe `AliasDefault(time, <my_time_type_def>)` so the behavior's only limited to the defaults `jsonschema` knows about? That lets me do something like `r.AliasDefault(jsonschema.TimeType, <my_time_type>)`.

**Comment by ekinanp** [comment]
Also, is there a reason for using `type#Name`? Was wondering if `jsonschema` could use `type#String` instead so that it uses the type's fully qualified name. That way, we're more likely to have unique definitions.

**Comment by alecthomas** [comment]
I think a generalised way of mapping Go types to `jsonschema.Type` would be useful, which would solve your issue. Something like a `Reflector.TypeMapping map[reflect.Type]*jsonschema.Type`. 

> Also, is there a reason for using type#Name? Was wondering if jsonschema could use type#String instead so that it uses the type's fully qualified name. That way, we're less likely to have conflicting types.

Seems reasonable, though I personally have not run into this issue.

PRs welcome.
