### ISSUE TITLE
Use "uuid" for uuid.UUID

### ISSUE THREAD

**Issue by tamuhey** [alecthomas/jsonschema#42]
Thanks for this great tool!

I think `uuid.UUID` should be parsed as `string (format uuid)`, because of [this doc](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types).

Now, `uuid.UUID` is parsed as follows:
```
{
    "items": {
        "type": "integer"
    },
    "maxItems": 16,
    "minItems": 16,
    "type": "array"
}
```

However, it should be parsed as follows:
```
{
    "type":"string"
    "format":"uuid"
}
```

Thanks,

**Comment by alecthomas** [comment]
There are many implementations of `UUID`, and none are in the standard library.

That said, some way of mapping a Go type to a type, as also discussed in #41.

**Comment by jackmahoney** [comment]
For future viewers, I used `jsonschema_extras:"format=uuid"` struct tag to make uuids work
