### ISSUE TITLE
Annotation for Enum

### ISSUE THREAD

**Issue by doertydoerk** [alecthomas/jsonschema#43]
Hello there!

I need to generate a JSON schema that has something like this:
```
"Salutation": {
		"type": "string",
		"enum": [
			"A",
			"B",
			"C"
		]
	}
```
The critical bit is the `enum` which, in my code is a bunch of const of type `Salutation` which in turn is a string alias.

I found no clue how to annotate an enum. Thanks for helping out!
Dirk

**Comment by sb2nov** [comment]
@doertydoerk how did you resolve this ?
