### ISSUE TITLE
How to generate enums

### ISSUE THREAD

**Issue by sb2nov** [alecthomas/jsonschema#49]
I saw the issue https://github.com/alecthomas/jsonschema/issues/43 but didn't see an answer to it. How should I generate a enum from a list of constants of type Foo.

**Comment by sb2nov** [comment]
CC @sguiheux @alecthomas

**Comment by sguiheux** [comment]
Hi @sb2nov, does TypeMapper do the job ?

`
TypeMapper: func(i reflect.Type) *Type {
				if i == reflect.TypeOf(<YOUR TYPE>) {
					return &Type{
						Type:   "string",
						Enum: <WHAT YOU WANT>
					}
				}
				return nil
			},
`

**Comment by sb2nov** [comment]
Thanks that worked perfectly.
