### ISSUE TITLE
How to get Schema as String?

### ISSUE THREAD

**Issue by jdoklovic** [alecthomas/jsonschema#5]
I need to write out the schema as a .json file but I can't figure out how to properly traverse the Schema object to get a string to write to the file.

Do you have an example?

**Comment by zamicol** [comment]
For future reference, here's an example:

```
type foo struct {
	Bar string `json:"bar,omitempty"`
}

func ExampleJSONSchema() {
	e := foo{}
	js := jsonschema.Reflect(e)
	jm, err := json.Marshal(js)
	fmt.Println(string(jm), err)
}

```
