### ISSUE TITLE
Maintain Sequence of Struct Fields

### ISSUE THREAD

**Issue by tooolbox** [alecthomas/jsonschema#50]
Using https://github.com/iancoleman/orderedmap for the `Type.Properties` field would preserve the sequence of reflected struct fields when outputting to JSON.  Currently the keys are alphabetized while marshaling.

The exact application I have is using the generated JSON schema to auto-generate a form, in which case I want to be able to control the sequence of the properties.

If @alecthomas is open to this, I will submit a PR!

Thanks.

**Comment by alecthomas** [comment]
Seems reasonable 👍
