### ISSUE TITLE
Arbitrary Fields

### ISSUE THREAD

**Issue by tooolbox** [alecthomas/jsonschema#52]
I would like the ability to add arbitrary additional fields to `jsonschema.Type` when it serializes to JSON.  I'm not referring to `AdditionalFields` and its behavior, but rather adding `"apple": "banana"` to a type if I so choose.

The application is feeding a JSON schema to something like [vue-json-schema-form](https://github.com/crickford/vue-json-schema-form) for [automatic form generation](https://codepen.io/crickford/pen/vQmKqY) in which case you need extra fields like `widget` to have full control over the output.

Thoughts:
- There isn't an existing field on `Type` that I could use for this somehow.
- I could anonymously embed `Type` in my own struct to add more fields, but then I lose the nesting and the rest of the behavior of the package.

My idea is to add a field, and a marshaling method ([playground](https://play.golang.org/p/rwGfs6QgW3-)) like this:
```go
package jsonschema

type Type struct {
    // ...
    Extras map[string]interface{} `json:"-"`
}

func (t Type) MarshalJSON() ([]byte, error) {
	type Type_ Type
	b, err := json.Marshal(Type_(t))
	if err != nil {
		return nil, err
	}
	if o.Extra == nil || len(t.Extra) == 0 {
		return b, nil
	}
	m, err := json.Marshal(t.Extra)
	if err != nil {
		return nil, err
	}
	if len(b) == 2 {
		return m, nil
	} else {
		b[len(b)-1] = ','
		return append(b, m[1:]...), nil
	}
}
```
Anything in `Extras` would then get merged into the JSON object for the `Type` itself.

The last step would be modifying the `keywords` util functions to have a default case of setting the key/value on the Extras map.

The idea is that:
```go
type Apple struct { 
    Banana string `jsonschema:"widget=mango"`
}

jsonschema.Reflect(Apple{})
```
...results in something like:
```json
{
  "properties": {
    "Banana": {
      "type": "string",
      "widget": "mango"
    }
  }
}
```

So then, two questions:
1. Yes, this is not necessarily per any spec that I'm aware of or could find, but I could see it being useful to people besides myself.  Are you open to a PR on this @alecthomas ?
2. Would you prefer a different word besides `Extras`, or do you have any comments on how you would prefer to implement this?

Thanks!

**Comment by alecthomas** [comment]
I'm not opposed to the idea, but I don't think we want the keywords in the `jsonschema` tag. There's precedent with `jsconschema_description` for adding another tag, so I'd create `jsonschema_extras` or something.

Seems not unreasonable.
