### ISSUE TITLE
Enum Annotation

### ISSUE THREAD

**Issue by tooolbox** [alecthomas/jsonschema#54]
- Technically a dup of #43 
- #49 concludes with the workaround of using TypeMapper, but this has limited workability if you have many enums.  It also defeats the point of reflection, to a degree.
- Not sure why #23 died
- I actually like the approach in #24 and it would be good in its own right (would cover the use case where your enum is already defined somehow and want to avoid duplicating it in the tag) but there is a simple case which can be covered with struct tags

Proposal:
```go
type Foo struct {
    Bar string `jsonschema:"enum=apple,enum=banana"`
}
```
```json
{
  "properties": {
    "Bar": {
      "type": "string",
      "enum": [
        "apple",
        "banana"
      ]
    }
  }
}
```
The strategy I would use is to use the `type` field as an indicator of what to coerce the values into.  So if we have `"type": "boolean"` then map `"true" -> true` or if `"type": "number"` then map `"5" -> 5` and so on.  I would tend to want to error if the field type is an array or object.

Let me know @alecthomas if you are open to a PR on this.

**Comment by alecthomas** [comment]
Yep I like it, thanks!
