### ISSUE TITLE
Specify custom type for struct

### ISSUE THREAD

**Issue by sb2nov** [alecthomas/jsonschema#59]
I've a gostruct which I implemented a custom Marshal function for hence when creating the json schema I would like to override the type to be string. 

Can I do that with tags? 

CC @sguiheux @alecthomas

**Comment by sb2nov** [comment]
Is there a way to match the output type of a custom marshal function

**Comment by sguiheux** [comment]
Maybe you can use oneof_type. It s not really for that but it can do the job. (See example in the ready or the test file.
