### ISSUE TITLE
Docs: readme has much better instructions than godoc

### ISSUE THREAD

**Issue by dcormier** [alecthomas/jsonschema#67]
The Readme is much more useful for figuring out how to create a schema than the godoc is. Perhaps move much of what's in the readme into the godoc as package documentation?

**Comment by alecthomas** [comment]
I prefer not to do this as it is difficult keeping them in sync. I'd be happy to have a link to the README in the godoc though.

**Comment by dcormier** [comment]
What if they weren't kept in sync, and the documentation was simply in the godoc, examples an all? Then the readme could simple point to the godoc for the documentation.

**Comment by alecthomas** [comment]
No, I prefer it the other way around.
