### ISSUE TITLE
Support ENUM for arrays

### ISSUE THREAD

**Issue by BorisRostovskiyDH** [alecthomas/jsonschema#89]
Not sure if I'm missing something, but enum  behavior for slice field the jsonschema tag default doesn't apply to the schema output.

Example:
> DisplayRule     []string `json:"displayRule" firestore:"display_rule" jsonschema:"enum=never_display,enum=display_when_data_found"

expected:
`"displayRule": {"items": { "type": "string", "enum": ["never_display", "display_when_data_found"]}, "type": "array"}`

got:
`displayRule": {"items":  {"type": "string"}, "type": "array"}`

**Comment by alecthomas** [comment]
Not sure, but it definitely works - there are tests for enums.

**Comment by BorisRostovskiyDH** [comment]
Unfortunately not. It works for simple string, but not for a slice of strings

**Comment by alecthomas** [comment]
Ah, that's possible. PRs are welcome.
