### ISSUE TITLE
map[int] could do better

### ISSUE THREAD

**Issue by s00500** [alecthomas/jsonschema#93]
Hey, awesome library, thanks a lot

I was using it to validate json and discovered that I could use random strings for map[int] types and still validate correctly, but then fail on unmarshal

So after plaing with the schema specs a little I figured that it could be fixed using something like this in reflect.go:

```
	case reflect.Map:
		var i int
		if t.Key() == reflect.TypeOf(i) {
			rt := &Type{
				Type: "object",
				PatternProperties: map[string]*Type{
					"^[0-9]+$": r.reflectTypeToSchema(definitions, t.Elem()),
				},
				AdditionalProperties: []byte("false"),
			}
			return rt
		}
		rt := &Type{
			Type: "object",
			PatternProperties: map[string]*Type{
				".*": r.reflectTypeToSchema(definitions, t.Elem()),
			},
		}
		delete(rt.PatternProperties, "additionalProperties")
		return rt
```

What do you think ? uint and other int types can not be used as string types in go as far as I know, so this should be an ok solution.

Should I prep a PR ? what do you think ?

Greetings

**Comment by alecthomas** [comment]
Aaah nice find. Yes that would be great, thanks.
