### ISSUE TITLE
 Why do all struct fields become "required"?

### ISSUE THREAD

**Issue by faustnord** [alecthomas/jsonschema#95]
Hey! You've created a cool tool! But I ran into one problem while using.
I have a "User" model where one field (for example) has a `jsonschema:" required "` tag.
The rest of the fields do not have such tags.

```
type User struct {
	ID        uint
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string `jsonschema:"required"`
	Surname   string
	Email     string
	Password  string
}
```

As a result, I get a result where all the fields of the structure are "required".

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/User",
  "definitions": {
    "User": {
      "required": [
        "ID",
        "CreatedAt",
        "UpdatedAt",
        "Name",
        "Surname",
        "Email",
        "Password"
      ],
      "properties": {
        "ID": {
          "type": "integer"
        },
        "CreatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "UpdatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "Name": {
          "type": "string"
        },
        "Surname": {
          "type": "string"
        },
        "Email": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}
```

It would be logical if only fields tagged with `jsonschema:" required "` became required.

**Comment by faustnord** [comment]
After examining the source code of the library, I discovered that this feature already exists in this tool.
By overriding the default Reflector and setting the RequiredFromJSONSchemaTags field to true, the required value will only become required if the `jsonschema:" required "` tag is present.

```
	reflector := jsonschema.Reflector{
		RequiredFromJSONSchemaTags: true,
	}
        reflector.Reflect(&User{})
```

I did not find this information in the documentation, as well as many other interesting features and settings.
Do you need help creating documentation?

**Comment by alecthomas** [comment]
Absolutely, all contributions are welcome :)
